/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package KafkaTest;

import com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer;
import com.amazonaws.services.schemaregistry.utils.AWSSchemaRegistryConstants;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.util.Properties;

public class App {
    public String getGreeting() {
        return "Hello Producer!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", AWSKafkaAvroSerializer.class);
        props.put(AWSSchemaRegistryConstants.AWS_REGION, "us-east-1");
        props.put(AWSSchemaRegistryConstants.SCHEMA_AUTO_REGISTRATION_SETTING, "true");
        props.put(AWSSchemaRegistryConstants.SCHEMA_NAME, "person-test-schema");
        props.put(AWSSchemaRegistryConstants.REGISTRY_NAME, "scott-test"); // If not passed, uses "default-registry"
        props.put(AWSSchemaRegistryConstants.CACHE_TIME_TO_LIVE_MILLIS, "86400000"); // If not passed, uses 86400000 (24 Hours)
        props.put(AWSSchemaRegistryConstants.CACHE_SIZE, "10"); // default value is 200

        Producer<String, Person> producer = new KafkaProducer<String, Person>(props);
        Person person = new Person(12345, "FirstName", "LastName", "email@example.com", 0, "", "");
        producer.send(new ProducerRecord<String, Person>("person-test-glue", String.valueOf(person.getId()), person));

        producer.close();
    }
}
